SELECT
    LOCALTIMESTAMP(0) AS "LOCALTIMESTAMP",
    CURRENT_TIMESTAMP(0) AS "CURRENT_TIMESTAMP";

SELECT
    LOCALTIME(0) AS "LOCALTIME",
    CURRENT_TIME(0) AS "CURRENT_TIME";

SELECT
    CURRENT_DATE AS "CURRENT_DATE";