DROP TABLE IF EXISTS p_characters;

START TRANSACTION;

CREATE TABLE p_characters (
    character_id INTEGER GENERATED BY DEFAULT AS IDENTITY (
        START
        WITH
            2000 INCREMENT BY 5
    ) PRIMARY KEY,
    name VARCHAR(16) NOT NULL
);

-- レコードの追加 (手動採番)
INSERT INTO
    p_characters (character_id, name)
VALUES
    (1, 'Alice'),
    (2, 'Bob');

-- レコードの追加 (自動採番)
INSERT INTO
    p_characters (name)
VALUES
    ('Carol'), -- 内部的に `1` を採番してPK制約違反が発生
    ('Dave');

ROLLBACK;